import json
import os
import tempfile
from fpdf import FPDF
from datetime import datetime

class ForensicReport(FPDF):
    def __init__(self, document_data):
        super().__init__()
        self.doc = document_data
        
    def header(self):
        # Header - Brand and Title
        self.set_font('helvetica', 'B', 20)
        self.set_text_color(0, 51, 102) # Canara Navy (approximate)
        self.cell(0, 10, 'KANARA BANK INTELLIGENCE', border=0, ln=1, align='C')
        
        self.set_font('helvetica', 'I', 14)
        self.set_text_color(243, 146, 0) # Canara Gold
        self.cell(0, 10, 'Automated Document Forensic Report', border=0, ln=1, align='C')
        self.ln(10)

    def footer(self):
        # Footer - Disclaimer and Page Number
        self.set_y(-25)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        disclaimer = (
            "DISCLAIMER: This report is generated by an automated AI system for Kanara Bank internal underwriting purposes. "
            "It should be used as a supplementary tool and does not replace final human judgement. "
            "The scores represent probabilistic indicators of potential manipulation, not definitive proof of fraud."
        )
        self.multi_cell(0, 4, disclaimer, align='C')
        self.set_y(-15)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

    def add_section_title(self, title):
        self.set_font('helvetica', 'B', 14)
        self.set_text_color(0, 51, 102)
        self.cell(0, 10, title, border=0, ln=1, align='L')
        # Add a subtle line below the title
        self.set_draw_color(200, 200, 200)
        self.line(self.get_x(), self.get_y(), self.w - 10, self.get_y())
        self.ln(5)

    def add_explanation(self, text):
        self.set_font('helvetica', '', 10)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def add_score_row(self, name, score, explanation):
        self.set_font('helvetica', 'B', 11)
        self.set_text_color(0, 0, 0)
        
        # Color coding for scores
        if score is None:
            score_text = "N/A"
            self.set_text_color(128, 128, 128)
        else:
            score_text = f"{score:.1f}/100"
            if score < 80:
                self.set_text_color(211, 47, 47) # Red for bad
            else:
                self.set_text_color(46, 125, 50) # Green for good
                
        self.cell(40, 8, name, border=0)
        self.cell(30, 8, score_text, border=0, ln=1)
        
        self.set_font('helvetica', 'I', 9)
        self.set_text_color(100, 100, 100)
        self.multi_cell(0, 5, explanation)
        self.ln(4)

def generate_forensic_report(doc) -> str:
    """Generates a PDF report and returns the file path to the temporary PDF."""
    pdf = ForensicReport(doc)
    pdf.add_page()
    
    # --- EXECUTIVE SUMMARY ---
    pdf.add_section_title("Executive Summary")
    
    pdf.set_font('helvetica', 'B', 11)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(40, 8, 'Document ID:', 0, 0)
    pdf.set_font('helvetica', '', 11)
    pdf.cell(0, 8, str(doc.id), 0, 1)
    
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(40, 8, 'File Name:', 0, 0)
    pdf.set_font('helvetica', '', 11)
    pdf.cell(0, 8, doc.filename, 0, 1)
    
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(40, 8, 'Upload Date:', 0, 0)
    pdf.set_font('helvetica', '', 11)
    upload_date = doc.created_at.strftime('%Y-%m-%d %H:%M:%S UTC') if doc.created_at else "Unknown"
    pdf.cell(0, 8, upload_date, 0, 1)
    
    pdf.set_font('helvetica', 'B', 11)
    pdf.cell(40, 8, 'Source Type:', 0, 0)
    pdf.set_font('helvetica', '', 11)
    source_val = doc.source.value if hasattr(doc.source, 'value') else str(doc.source)
    pdf.cell(0, 8, source_val, 0, 1)

    pdf.ln(5)
    
    # Final Score & Status Block
    pdf.set_fill_color(245, 245, 245)
    pdf.set_font('helvetica', 'B', 14)
    status_text = doc.status.upper().replace('_', ' ')
    
    # Status styling
    if "REJECT" in status_text:
        pdf.set_text_color(211, 47, 47)
    elif "FLAGGED" in status_text:
        pdf.set_text_color(243, 146, 0)
    else:
        pdf.set_text_color(46, 125, 50)
        
    score_display = f"{doc.fraud_score:.1f}/100" if doc.fraud_score is not None else "ERROR"
    pdf.cell(0, 15, f'FINAL FRAUD SCORE: {score_display}   |   STATUS: {status_text}', border=1, ln=1, align='C', fill=True)
    pdf.ln(10)
    
    # --- FORENSIC ANALYSIS BREAKDOWN ---
    pdf.add_section_title("Forensic Analysis Breakdown")
    pdf.add_explanation(
        "The following metrics measure the structural and visual integrity of the document. "
        "A score of 100 means no anomalies were detected in that category. Lower scores indicate "
        "increasing probability of digital forgery or tampering."
    )
    
    scores = {}
    if hasattr(doc, 'scores') and doc.scores:
        try:
            scores = json.loads(doc.scores)
        except:
            pass

    pdf.set_font('helvetica', 'B', 11)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 8, "Understanding the Parameters:", ln=1)
    
    pdf.add_score_row("ELA Analysis", scores.get('ela'), 
                      "Error Level Analysis detects inconsistencies in pixel compression. "
                      "If a document was modified (e.g., text pasted over an image), the new elements "
                      "will compress differently than the original background, triggering a low score.")
    
    pdf.add_score_row("Edge Detection", scores.get('edge'), 
                      "Analyzes the image for sharp, unnatural rectangular boundaries. "
                      "This detects if someone took a physical photo of another photo, or glued/pasted "
                      "a box of text onto a physical document before scanning.")
                      
    pdf.add_score_row("Copy-Move", scores.get('copy_move'), 
                      "Detects identical cloned areas within the same document. Forgers often copy "
                      "blank background areas to cover up existing text or signatures.")
                      
    pdf.add_score_row("OCR & Logic", scores.get('ocr'), 
                      "Extracts text using AI and performs logical validations (e.g., verifying that "
                      "Gross = Net + Deductions, or checking chronological consistency of dates).")
                      
    pdf.add_score_row("PDF Forensics", scores.get('pdf'), 
                      "Analyzes the internal metadata and structure of a PDF file. Documents created "
                      "using PDF editors (like Adobe Illustrator or iLovePDF) rather than standard scanners "
                      "will be heavily penalized here.")

    if 'signature' in scores and scores['signature'] is not None:
        pdf.add_score_row("Signature Forensics", scores.get('signature'),
                          "Analyzes ink strokes, pressure, and micro-alterations in the signature block "
                          "to detect digital tracing or copy-pasting of signatures.")

    pdf.ln(5)
    
    # --- ANOMALIES LOG ---
    pdf.add_page()
    pdf.add_section_title("Detailed Anomalies Log")
    
    flags = []
    if doc.flags:
        try:
            flags = json.loads(doc.flags)
        except:
            flags = [doc.flags]
            
    if not flags:
        pdf.set_font('helvetica', 'I', 11)
        pdf.set_text_color(46, 125, 50)
        pdf.cell(0, 10, "No severe anomalies detected. Document integrity verified.", ln=1)
    else:
        pdf.set_font('helvetica', '', 11)
        pdf.set_text_color(211, 47, 47)
        for flag in flags:
            pdf.set_x(10)
            pdf.multi_cell(0, 8, f"- {flag}")
            
    # Output to temporary file
    temp_fd, temp_path = tempfile.mkstemp(suffix=".pdf")
    os.close(temp_fd)
    pdf.output(temp_path)
    
    return temp_path
